### ISSUE TITLE
sre_compile_test.py failed

### ISSUE THREAD

**Issue by led02** [dropbox/pyston#707] opened 2015-07-15 11:54 UTC
When running "make check", I get an error in "sre_compile_test.py" for test run 5 and 6.

Executing the respective script with Python 2.7.9 [GCC 4.9.2] produces:
    None
    None
    ('b',)
    0
    10000
    20000
    30000
    40000
    50000
    60000
    70000
    80000
    90000
    Traceback (most recent call last):
      File "sre_compile_test.py", line 18, in <module>
        print sre_compile._optimize_charset(charset, identity)
    TypeError: _optimize_charset() takes exactly 4 arguments (2 given)

The output of Pyston is:
    None
    None
    ('b',)
    0
    10000
    20000
    30000
    40000
    50000
    60000
    70000
    80000
    90000
    [('bigcharset', [2, 16843008L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 16843009L, 0L, 0L, 0L, 0L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L, 4294967295L])]

Testing has been done on Debian jesse in a VMware virtual machine.

**Comment by undingen** [comment] 2015-07-15 12:22
The problem is that the CPython 2.7.9 lib is not compatible with this test.
We should skip this test on 2.7.9 but I'm not sure how to do that...
But you can ignore the error meanwhile.

**Comment by led02** [comment] 2015-07-15 12:29
Thanks for the quick answer. I will go on trying it on some of my projects :)

**Comment by kmod** [comment] 2015-07-16 00:43
Hopefully should be fixed now, though I guess this kind of thing will continue to be an issue since we don't test against different versions of CPython.

thanks for the report!

**Closed** 2015-07-16 00:43 UTC
